---
- name: Configure Service Environment Variables
  ansible.builtin.template:
    src: klipper.env.j2
    dest: '{{ printer_data_path }}/systemd/klipper.env'
    mode: '0644'
  notify: Restart Klipper
  tags:
    - klipper
