---
- name: Download Kiuah
  ansible.builtin.git:
    repo: 'https://github.com/dw-0/kiauh'
    dest: '{{ printer_path }}/kiauh'
    version: 'master'
  tags:
    - klipper

- name: Configure Service Environment Variables
  ansible.builtin.template:
    src: klipper.env.j2
    dest: '{{ printer_data_path }}/systemd/klipper.env'
    mode: '0644'
  notify: Restart Klipper
  tags:
    - klipper
