---
- name: Configure Facts
  ansible.builtin.include_tasks:
    file: set-facts.yaml
  tags:
    - global
    - klipper
    - klipper-config
    - moonraker
    - fluidd
    - klipper-screen
    - crowsnest

- name: Install Common Packages
  ansible.builtin.apt:
    name:
      - vim
      - git
      - curl
      - btop
      - htop
      - python3-serial
    state: present
    update_cache: false
  become: true
  tags:
    - global

- name: Set Hostname
  ansible.builtin.hostname:
    name: "{{ ansible_hostname }}"
  become: true
  tags:
    - global

- name: Enable systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: true
    state: started
  become: true
  tags:
    - global

- name: Disable systemd-networkd-wait-online.service
  ansible.builtin.systemd:
    name: systemd-networkd-wait-online.service
    enabled: false
  become: true
  tags:
    - global

- name: Create CAN udev rules
  ansible.builtin.template:
    src: 10-can.rules.j2
    dest: /etc/udev/rules.d/10-can.rules
    mode: '0644'
  become: true
  tags:
    - global

- name: Create CAN network configuration
  ansible.builtin.template:
    src: 25-can.network.j2
    dest: /etc/systemd/network/25-can.network
    mode: '0644'
  become: true
  tags:
    - global

- name: Check if Reboot is Required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot
  tags:
    - global

- name: Reboot
  ansible.builtin.reboot:
    msg: "Reboot By Ansible"
    connect_timeout: 5
    reboot_timeout: 300 # 5 Minutes
    pre_reboot_delay: 0 # Reboot Immediately
    post_reboot_delay: 30
    test_command: uptime
  become: true
  tags:
    - global
  when: reboot.stat.exists
  # when: reboot.stat.exists and not printer_active_print
