---
- name: Set Ansible User
  ansible.builtin.set_fact:
    ansible_user: "{{ ansible_env.USER }}"
  tags:
    - global
    - klipper
    - klipper-config
    - moonraker
    - fluidd
    - klipper-screen
  when: ansible_user is not defined
- name: Set Directory Paths
  ansible.builtin.set_fact:
    printer_path: "/printer/"
    printer_data_path: /printer/printer_data
    klipper_path: /printer/klipper
    klipper_env_path: /printer/klippy_env
    moonraker_path: /printer/moonraker
    moonraker_env_path: /printer/moonraker_env
  tags:
    - global
    - klipper
    - klipper-config
    - moonraker
    - fluidd
    - klipper-screen
- name: Retrieve Current Printer Status
  ansible.builtin.uri:
    url: "http://{{ ansible_host }}:7125/printer"
    method: GET
    return_content: true
    status_code: 200
    force: false
  check_mode: false
  ignore_errors: true
  register: printer_status
  tags:
    - global
    - klipper
    - klipper-config
    - moonraker
    - fluidd
    - klipper-screen
- name: Register Current Printer Status
  ansible.builtin.set_fact:
    printer_active_print: "{{ printer_status.json.state.flags.printing or printer_status.json.state.flags.paused or printer_status.json.state.flags.pausing }}"
  tags:
    - global
    - klipper
    - klipper-config
    - moonraker
    - fluidd
    - klipper-screen
  when: printer_status.status == 200

- name: Register Current Printer Status
  ansible.builtin.set_fact:
    printer_active_print: "false"
  tags:
    - global
    - klipper
    - klipper-config
    - moonraker
    - fluidd
    - klipper-screen
  when: printer_status.status != 200

- name: Configure File Paths
  ansible.builtin.set_fact:
    klipper_cfg_path: "{{ printer_data_path }}/configs"
    printer_cfg_path: "{{ printer_data_path }}/configs/{{ inventory_hostname }}/printer.cfg"
    moonraker_cfg_path: "{{ printer_data_path }}/configs/{{ inventory_hostname }}/moonraker.conf"
  tags:
    - global
    - klipper
    - klipper-config
    - moonraker
    - fluidd
    - klipper-screen
