---
- name: Configure Moonraker Service Environment Variables
  ansible.builtin.template:
    src: moonraker.env.j2
    dest: '{{ printer_data_path }}/systemd/moonraker.env'
    mode: '0644'
  notify: Restart Moonraker
  tags:
    - moonraker
