---
- name: Copy Printer Configuration
  ansible.posix.synchronize:
    src: "./../../../../"
    dest: "{{ cfg_repo_path }}/"
    rsync_opts:
      - "--exclude=.venv"
      - "--exclude=.ansible"
      - "--exclude=tmp"
      - "--exclude=.~tmp~"
  notify: Restart Klipper
  tags:
    - klipper-config

- name: Symlink Printer Configuration
  ansible.builtin.file:
    src: "{{ cfg_repo_path }}/configs"
    dest: "{{ printer_data_path }}/config"
    state: link
  tags:
    - klipper-config
