---
- name: Restart Klipper
  ansible.builtin.systemd:
    name: klipper
    enabled: true
    daemon_reload: true
    state: restarted
  # when: not printer_active_print
  become: true
  tags:
    - klipper
